#!/bin/bash
TS=`date "+%FT%T"`
for tape in $(cat tapes_list_test.txt)
do
        if [ ! -f $tape.hpss.staged.txt ]
        then
                lsvol -i1 -v $tape &> output.txt
                sed -n 's,.*/ghi_managed/hpss_ghi,/ghi_managed/hpss_ghi,p' output.txt | egrep 'AGG|NON'  > $tape.txt
                echo -e "`date "+%FT%T"` lsvol in $tape created\r " >> logfile.log
                echo -e "`date "+%FT%T"` copying to disk from $tape\r"
                rm -f output.txt
                /usr/local/hpss/bin/hpssstagelist $tape.txt &> $tape.hpss.staged.txt
                echo -e "`date "+%FT%T"` $tape copied to disk\r " >> logfile.log
        fi
        echo -e "connecting to r1ghi01"
        ssh -t r1ghi01  "/ghi/MPCDF/HPSS/GHI1/FilesystemLists/2018/02/cleanFiles/ghistage.sh $tape"
        echo -e "`date "+%FT%T"` files in $tape staged in ghi\r " >> logfile.log
        echo -e "checking status of staging in r1ghi01"
        ssh -t r1ghi01  "/ghi/MPCDF/HPSS/GHI1/FilesystemLists/2018/02/cleanFiles/ghicheck.sh $tape"
        echo -e "creating backup file "
        ssh -t r1ghi01  "/ghi/MPCDF/HPSS/GHI1/FilesystemLists/2018/02/cleanFiles/tsmbackup.sh $tape"
        #echo -e "checking status of backup"
        #ssh -t r1ghi01  "while [ ! -f $tape.backup_done ]; do echo -e "waiting for the backup of $tape"; sleep 30; done"
        #echo -e "`date "+%FT%T"` $tape backup done \r" >> logfile.log
        #echo -e "checking status of backup & purge files"
        #ssh -t r1ghi01 "/ghi/MPCDF/HPSS/GHI1/FilesystemLists/2018/02/cleanFiles/checkpurge.sh $tape"
        #echo -e "`date "+%FT%T"` files in $tape purged \r" >> logfile.log
done