#!/bin/bash

tape=$1
dirtapes=/ghi/MPCDF/HPSS/GHI1/FilesystemLists/2018/02/cleanFiles/tapes
dirout=/ghi/MPCDF/HPSS/GHI1/FilesystemLists/2018/02/cleanFiles/output_files

if [ ! -f $dirout/tobackup/$tape.tobackup.txt ]
then
        for agg in $(cat $dirout/$tape.tostage.txt)
        do
         sed '$a\' $dirtapes/$tape/$agg | sed -e 's,^/ghi,Z:,' -e 's,/,\\,g' -e 's,^,",' -e 's,$,",' >> $dirout/tobackup/$tape.tobackup.txt
        done
echo -e "`date "+%FT%T"` $tape.tobackup.txt created\n"
echo -e "`date "+%FT%T"` $tape.tobackup.txt created" >> $dirout/ghistage.log
else
echo -e "`date "+%FT%T"` $tape.tobackup.txt exists\n"
echo -e "`date "+%FT%T"` $tape.tobackup.txt exists" >> $dirout/ghistage.log
fi
