#!/bin/bash

dirout=/cygdrive/z/MPCDF/HPSS/GHI1/FilesystemLists/2018/02/cleanFiles/output_files
dirbc="/cygdrive/z/MPCDF/HPSS/GHI1/FilesystemLists/2018/02/cleanFiles/output_files/tobackup"
wdirbc="Z:\\MPCDF\\HPSS\\GHI1\\FilesystemLists\\2018\\02\\cleanFiles\\output_files\\tobackup"
tsmdir="/cygdrive/c/Program\ Files/Tivoli/TSM/baclient"
r1dir="/cygdrive/c/R1GHI"
edir="/cygdrive/e/smar/check_files"
cdir="/cygdrive/c/Users/smar"
#cd "/cygdrive/c/Program Files/Tivoli/TSM/baclient"
cd $tsmdir

while true
do
        backupfiles=`ls $dirbc`
        nfiles=`ls $dirbc | wc -l`
        echo "$backupfiles"
        if [ $nfiles -gt 0 ]
        then
                for file in $backupfiles
                do
                        tape=`echo ${file:0:8}`
                        echo $tape
                        if [ ! -f $r1dir/$tape*]
                        then
                            /cygdrive/c/Program\ Files/Tivoli/TSM/baclient/dsmc incremental -filelist=\"$bcfile\" > $cdir/$tape\_log.txt
                            bcfile=$wdirbc\\$file
                            echo "dsmc incremental -filelist=\"$bcfile\" > $edir/$tape.check.txt"
                            /cygdrive/c/Program\ Files/Tivoli/TSM/baclient/dsmc query backup -filelist=\"$bcfile\" > $edir/$tape\_check.txt
                            logfiles=`grep "Normal File" $cdir/$tape\_log.txt | wc -l`
                            checkfiles=`grep DEFAULT $edir/$tape\_check.txt | wc -l`
                            ofiles=`wc -l < $dirbc/$tape.tobackup.txt`
                            if [ $logfiles -eq $checkfiles ] && [ $checkfiles -eq $ofiles ]
                            then
                                touch /cygdrive/c/R1GHI/$tape.txt
                                echo -e "`date "+%FT%T"` backup done for $tape\r" >> $edir/poldbackup_log
                            else
                                touch /cygdrive/c/R1GHI/$tape.error.txt
                                echo -e "`date "+%FT%T"` ERROR in $tape backup\r" >> $edir/poldbackup_log
                            fi
                        fi
                done
        fi
        echo "waiting"
        sleep 30
done




